<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.3.8 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Fri, 19 Nov 2010 20:42:51 -0500
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '127.0.0.1';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['pmadb'] = 'pmadb';
$cfg['Servers'][$i]['controluser'] = 'pmadb';
$cfg['Servers'][$i]['controlpass'] = 'changeit';
$cfg['Servers'][$i]['bookmarktable'] = 'pma_bookmark';
$cfg['Servers'][$i]['relation'] = 'pma_relation';
$cfg['Servers'][$i]['table_info'] = 'pma_table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma_table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma_pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma_column_info';
$cfg['Servers'][$i]['history'] = 'pma_history';
$cfg['Servers'][$i]['designer_coords'] = 'pma_designer_coords';/*
$cfg['Servers'][$i]['tracking'] = 'pma_tracking';
*/


/* End of servers configuration */

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ForceSSL'] = true;
$cfg['LoginCookieRecall'] = false;
$cfg['Export'] = array (
  'compression' => 'bzip2',
  'charset' => 'utf-8',
);
$cfg['DefaultLang'] = 'en-utf-8';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '{gIATs3mlHy+Gd~FE3mNKVYv{ubK*U0V^1lX+T={^QP+-('; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */
?>